kind: pipeline
name: default

type: docker
steps:
  - name: test
    image: python:3.7-alpine
    commands:
      - pip install -r requirements.txt
      - pytest
  - name: docker
    image: plugins/docker
    settings:
      repo: happydevelopperfr/python-administrative-communes
      username:
        from_secret: DOCKER_HUB_LOGIN
      password:
        from_secret: DOCKER_HUB_TOKEN
